ForumApplication/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Forum.Core.Interfaces.Managers;
using Forum.Core.Interfaces.UnitOfWork;
using Forum.Core.Models;
using ForumApplication.Models;
using Microsoft.Owin.Security.Provider;

namespace ForumApplication.Controllers
{
    public class TopicController : Controller
    {
        private readonly ITopicManager _topicManager;
        private readonly ITopicStarterManager _topicStarterManager;
        private readonly IUnitOfWork _unitOfWork;

        public TopicController(ITopicManager topicManager, ITopicStarterManager topicStarterManager, IUnitOfWork unitOfWork)
        {
            _topicManager = topicManager;
            _topicStarterManager = topicStarterManager;
            _unitOfWork = unitOfWork;
        }

        private TopicModel GetModel(int topicId)
        {
            var topic = _topicManager.GetTopicById(topicId);
            var model = new TopicModel()
            {
                TopicId = topic.TopicId,
                TopicMessage = topic.TopicMessage,
                TopicName = topic.TopicName,
                TopicDateTime = topic.TopicDateTime,
                TopicStarterId = topic.TopicStarterId
            };
            return model;
        }

        // GET: Topic
        public ActionResult Index()
        {
            var topics = _topicManager.GetAllTopics();
            return View(topics);
        }

        [Authorize]
        [HttpGet]
        public ActionResult AddNewTopic()
        {
            var topicStarter = _topicStarterManager.GetAllTopicStarters()
                .FirstOrDefault(x => x.TopicStarterEmail.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase));
            var topic = new TopicModel();
            if (topicStarter != null)
            {
                ViewBag.IsAuthenticated = true;
                ViewBag.IsTopicStarter = true;
                topic.TopicStarterId = topicStarter.TopicStarterId;
            }
            return View("TopicDetails", topic);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddNewTopic(TopicModel topic)
        {
            if (ModelState.IsValid)
            {
                _topicManager.AddTopic(topic.TopicName, topic.TopicMessage, topic.TopicStarterId, DateTime.Now);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult EditTopic(int topicId)
        {
            var model = GetModel(topicId);
            ViewBag.IsAuthenticated = ControllerContext.HttpContext.Request.IsAuthenticated;
            ViewBag.IsTopicStarter = _topicStarterManager.GetTopicStarterById(model.TopicStarterId)
                .TopicStarterEmail == User.Identity.Name;
            return View("TopicDetails", model);
        }

        [HttpPost]
        public ActionResult EditTopic(TopicModel topicModel)
        {
            if (ModelState.IsValid)
            {
                _topicManager.EditTopic(topicModel.TopicId, topicModel.TopicName, topicModel.TopicMessage, topicModel.TopicStarterId, topicModel.TopicDateTime);
                _unitOfWork.Save();
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult DeleteTopic(int topicId)
        {
            this._topicManager.DeleteTopic(topicId);
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpGet]
        public ActionResult CreateNewTopicComment(int topicId)
        {
            var currentTopicId = topicId;
            return RedirectToAction("AddNewTopicComment", "TopicComment", new { topicId = currentTopicId });
        }
    }
}

ForumApplication/Controllers/TopicStarterController.cs
using System.Web;
using System.Web.Mvc;
using Forum.Core.Enums;
using Forum.Core.Interfaces.Managers;
using ForumApplication.Models;

namespace ForumApplication.Controllers
{
    public class TopicStarterController : Controller
    {
        private readonly ITopicStarterManager _topicStarterManager;
        // GET: TopicStarter
        public TopicStarterController(ITopicStarterManager topicStarterManager)
        {
            _topicStarterManager = topicStarterManager;
        }
        public ActionResult Index()
        {
            return View();
        }

        private TopicStarterModel GetModel(int topicId)
        {
            var topicStarter = _topicStarterManager.GetTopicStarterById(topicId);
            var model = new TopicStarterModel()
            {
               TopicStarterNick = topicStarter.TopicStarterNick,
               Avatar = topicStarter.Avatar,
               TopicStarterEmail = topicStarter.TopicStarterEmail,
               TopicStarterId = topicStarter.TopicStarterId,
               ForumRankId = (ForumRankEnum)topicStarter.ForumRankId,
               ForumRoleId = (ForumRoleEnum)topicStarter.ForumRankId,
               ImageMimeType = topicStarter.ImageMimeType
            };
            return model;
        }

        [HttpGet]
        public ActionResult AddNewTopicStarter()
        {
            var topicStarter = new TopicStarterModel
            {
                TopicStarterEmail = User.Identity.Name
            };
            return View("TopicStarterDetails",topicStarter);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddNewTopicStarter(TopicStarterModel topicStarter, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    topicStarter.Avatar = new byte[image.ContentLength];
                    image.InputStream.Read(topicStarter.Avatar, 0, image.ContentLength);
                    topicStarter.ImageMimeType = image.ContentType;
                }
                var forumRoleId = (int) topicStarter.ForumRoleId;
                var forumRankId = (int) topicStarter.ForumRankId;
                _topicStarterManager.AddTopicStarter(forumRoleId, forumRankId,
                    topicStarter.Avatar, topicStarter.ImageMimeType, topicStarter.TopicStarterNick,topicStarter.TopicStarterEmail);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult GetAvatar(int topicStarterId)
        {
            var topicStarter = _topicStarterManager.GetTopicStarterById(topicStarterId);
            if (topicStarter != null)
            {
                return File(topicStarter.Avatar, topicStarter.ImageMimeType);
            }
            return null;
        }

        [HttpGet]
        public ActionResult GetUserDetails(int topicStarterId)
        {
            var model = GetModel(topicStarterId);
            return PartialView("UserDetails",model);
        }

    }
}

ForumApplication/Views/Topic/Index.cshtml
@model Forum.Core.Models.Topic[]

@{
    ViewBag.Title = "Topics";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>Topics</h2>

ForumApplication/Views/Topic/TopicDetails.cshtml
@model ForumApplication.Models.TopicModel
@{
    ViewBag.Title = "Topic Details";
    var action = Model.TopicId > 0 ? "EditTopic" : "AddNewTopic";
    var header = Model.TopicId > 0 ? "Edit Topic" : "Create Topic";
    var buttonText = Model.TopicId > 0 ? "Save" : "Create";
    var isAuthenticated = ViewBag.IsAuthenticated;
    var isTopicStarter = ViewBag.IsTopicStarter;
    //var summerNoteStatus = isTopicStarter & isAuthenticated ? "enable" : "disable";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
    @Styles.Render("~/Content/summernote")
    @*<link href="~/Content/jquery-ui.css" rel="stylesheet">*@
}
<div class="container body-content">
    <div class="container body-content" style="padding-top: 15px;">
        <div class="col-md-4">
            @Html.Action("GetUserDetails", "TopicStarter", new { topicStarterId = @Model.TopicStarterId })
        </div>
        <div class="col-md-8">
            @using (Html.BeginForm(action, "Topic", FormMethod.Post, new { @class = "form-horizontal", @id = "editTopic" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(m => m.TopicId)
                @Html.HiddenFor(m => m.TopicStarterId)
                <div class="form-group">
                    @if (isTopicStarter)
                    {
                        <div style="display: flex; justify-content: space-between;">
                            <h4>@header</h4>
                            @Html.ActionLink("Delete Topic", "DeleteTopic", "Topic", new { topicId = Model.TopicId }, new { @class = "btn btn-danger", @style = "height: 33px;" })
                        </div>
                        <hr />
                        @Html.LabelFor(m => m.TopicName, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.TopicName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TopicName, "", new { @class = "text-danger" })
                    }
                    else
                    {
                        <h3 class="text-center">@Html.DisplayTextFor(m => m.TopicName)</h3>
                    }
                </div>
                <div class="form-group">
                    @if (isTopicStarter)
                    {
                        @Html.LabelFor(m => m.TopicMessage, new { @class = "control-label" })
                        @Html.TextAreaFor(m => m.TopicMessage, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TopicMessage, "", new { @class = "text-danger" })
                    }
                    else
                    {
                        @Html.Raw(@Model.TopicMessage)
                    }
                </div>

                if (isTopicStarter && Model.TopicId > 0)
                {
                    <div class="form-group" style="text-align: center;">
                        <input type="submit" value="@buttonText" class="btn btn-primary" style="width: 75px;" />
                        <button type="button" id="btnAnswer" class="btn btn-info">Answer</button>
                    </div>
                }
                if (isTopicStarter && Model.TopicId == 0)
                {
                    <div class="form-group">
                        <input type="submit" value="@buttonText" class="btn btn-primary" />
                    </div>
                }

                if (!isTopicStarter & isAuthenticated)
                {
                    <div class="form-group text-right">
                        <button type="button" id="btnAnswer" class="btn btn-primary">Answer</button>
                    </div>
                }
                if (isAuthenticated)
                {
                    <div id="addNewComment" style="z-index: 500; height: 275px;">
                        @Html.Action("AddNewTopicComment", "TopicComment", new { topicId = Model.TopicId })
                    </div>
                }
            }
        </div>
    </div>
    <div>
        @Html.Action("GetTopicComments", "TopicComment", new { topicId = Model.TopicId })
    </div>
</div>


@section scripts{
    @Scripts.Render("~/bundles/summernote")
    @Scripts.Render("~/bundles/jquery-ui")
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#TopicMessage").summernote({
            height: 200,
            focus: true,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['fontname', ['fontname']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture']],
                ['view', ['codeview']]
            ]
        });
    });
    $(document).ready(function () {
        $("#addNewComment").dialog({
            autoOpen: false,
            height: 380,
            width: 800,
            title: "Comment Editor",
            show: {
                effect: "blind",
                duration: "1000"
            },
            hide: {
                effect: "explode",
                duration: "1000"
            },
            modal: false,
            resizable: false,
            dialogClass: 'no-close success-dialog',
            position: { my: "center", at: "bottom", of: window }
        });
        $("#btnAnswer").click(function () {
            $("#addNewComment").dialog("open");
        });
        $("div.ui-dialog.ui-widget.ui-widget-content.ui-corner-all.ui-front.no-close.success-dialog.ui-draggable.ui-resizable")
            .attr('id', 'modalCmtEdt');
    }
    );
</script>