ForumApplication/Controllers/TopicCommentController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Forum.Core.Interfaces.Managers;
using Forum.Core.Interfaces.UnitOfWork;
using Forum.Core.Models;
using ForumApplication.Models;

namespace ForumApplication.Controllers
{
    public class TopicCommentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ITopicCommentManager _topicCommentManager;
        private readonly ITopicStarterManager _topicStarterManager;
        public TopicCommentController(IUnitOfWork unitOfWork, ITopicCommentManager topicCommentManager, ITopicStarterManager topicStarterManager)
        {
            _unitOfWork = unitOfWork;
            _topicCommentManager = topicCommentManager;
            _topicStarterManager = topicStarterManager;
        }
        // GET: TopicComment
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        [HttpGet]
        public ActionResult AddNewTopicComment(int topicId)
        {
            var topicStarter = _topicStarterManager.GetAllTopicStarters()
                .FirstOrDefault(x => x.TopicStarterEmail.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase));
            var topicStarterId = topicStarter.TopicStarterId;
            var model = new TopicCommentModel
            {
                TopicId = topicId,
                TopicStarterId = topicStarterId
            };
            return PartialView("TopicCommentDetails", model);
        }
        [Authorize]
        [HttpPost]
        public ActionResult AddNewTopicComment(TopicCommentModel model)
        {
            if (ModelState.IsValid)
            {
                _topicCommentManager.AddTopicComment(DateTime.Now, model.TopicAttachment, model.AttachmentMimeType,
                    model.TopicCommentMessage, model.TopicId, model.TopicStarterId);
                _unitOfWork.Save();
                return RedirectToAction("EditTopic", "Topic", new { topicId = model.TopicId });
            }
            return RedirectToAction("AddNewTopicComment", model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult EditTopicComment(int topicCommentId)
        {
            var model = GetModel(topicCommentId);
            return PartialView("TopicCommentDetails", model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditTopicComment(TopicCommentModel model)
        {
            if (ModelState.IsValid)
            {
                _topicCommentManager.EditTopicComment(model.TopicCommentId, DateTime.Now, model.TopicAttachment,
                    model.AttachmentMimeType, model.TopicCommentMessage, model.TopicId, model.TopicStarterId);
                _unitOfWork.Save();
                return RedirectToAction("EditTopic", "Topic",new {topicId = model.TopicId });
            }
            return PartialView("TopicCommentDetails", model);
        }

        [HttpGet]
        public ActionResult GetTopicComments(int topicId)
        {
            TopicComment[] topicCommentsList = _topicCommentManager.GetAllComments().Where(x => x.TopicId == topicId).ToArray();
            ViewBag.CommentOwnerId = null;
            if (ControllerContext.HttpContext.Request.IsAuthenticated)
            {
                var topicStarter = _topicStarterManager.GetAllTopicStarters()
                    .FirstOrDefault(m => m.TopicStarterEmail == User.Identity.Name);
                if (topicStarter != null)
                {
                    ViewBag.CommentOwnerId = topicStarter.TopicStarterId;
                }
            }
            return PartialView(topicCommentsList);
        }

        private TopicCommentModel GetModel(int id)
        {
            var record = _topicCommentManager.GetTopicCommentById(id);
            var model = new TopicCommentModel
            {
                TopicId = record.TopicId,
                TopicCommentId = record.TopicCommentId,
                TopicCommentMessage = record.TopicCommentMessage,
                TopicStarterId = record.TopicStarterId
            };
            return model;
        }
    }
}

ForumApplication/Controllers/TopicStarterController.cs
using System.Web;
using System.Web.Mvc;
using Forum.Core.Enums;
using Forum.Core.Interfaces.Managers;
using ForumApplication.Models;

namespace ForumApplication.Controllers
{
    public class TopicStarterController : Controller
    {
        private readonly ITopicStarterManager _topicStarterManager;
        // GET: TopicStarter
        public TopicStarterController(ITopicStarterManager topicStarterManager)
        {
            _topicStarterManager = topicStarterManager;
        }
        public ActionResult Index()
        {
            return View();
        }

        private TopicStarterModel GetModel(int topicId)
        {
            var topicStarter = _topicStarterManager.GetTopicStarterById(topicId);
            var model = new TopicStarterModel()
            {
               TopicStarterNick = topicStarter.TopicStarterNick,
               Avatar = topicStarter.Avatar,
               TopicStarterEmail = topicStarter.TopicStarterEmail,
               TopicStarterId = topicStarter.TopicStarterId,
               ForumRankId = (ForumRankEnum)topicStarter.ForumRankId,
               ForumRoleId = (ForumRoleEnum)topicStarter.ForumRankId,
               ImageMimeType = topicStarter.ImageMimeType
            };
            return model;
        }

        [HttpGet]
        public ActionResult AddNewTopicStarter()
        {
            var topicStarter = new TopicStarterModel
            {
                TopicStarterEmail = User.Identity.Name
            };
            return View("TopicStarterDetails",topicStarter);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddNewTopicStarter(TopicStarterModel topicStarter, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    topicStarter.Avatar = new byte[image.ContentLength];
                    image.InputStream.Read(topicStarter.Avatar, 0, image.ContentLength);
                    topicStarter.ImageMimeType = image.ContentType;
                }
                var forumRoleId = (int) topicStarter.ForumRoleId;
                var forumRankId = (int) topicStarter.ForumRankId;
                _topicStarterManager.AddTopicStarter(forumRoleId, forumRankId,
                    topicStarter.Avatar, topicStarter.ImageMimeType, topicStarter.TopicStarterNick,topicStarter.TopicStarterEmail);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult GetAvatar(int topicStarterId)
        {
            var topicStarter = _topicStarterManager.GetTopicStarterById(topicStarterId);
            if (topicStarter != null)
            {
                return File(topicStarter.Avatar, topicStarter.ImageMimeType);
            }
            return null;
        }

        [HttpGet]
        public ActionResult GetUserDetails(int topicStarterId)
        {
            var model = GetModel(topicStarterId);
            return PartialView("UserDetails",model);
        }

    }
}

ForumApplication/Views/TopicComment/GetTopicComments.cshtml
@using Forum.Core.Models;
@model TopicComment[]
@{
    var commentOwnerId = ViewBag.CommentOwnerId;
}
@section head{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/start/jquery-ui.css">
}
@if (Model != null && Model.Any())
{
    foreach (var item in Model)
    {
        <div class="container body-content">
            <hr />
            <div class="col-md-4">
                @Html.Action("GetUserDetails", "TopicStarter", new { topicStarterId = item.TopicStarterId })
            </div>
            <div class="col-md-8">
                <h6 class="text-right">
                    @Html.Raw(item.TopicCommentDateTime.ToShortDateString() + " " +
                                                  item.TopicCommentDateTime.ToShortTimeString())
                </h6>
                @Html.Raw(item.TopicCommentMessage)
                @if (commentOwnerId != null && item.TopicStarterId == commentOwnerId)
                {
                    <div class="form-group text-right" style="margin: 0;">
                        <button type="button" id="btnEdit" class="btn btn-primary">Edit</button>
                    </div>
                    <div id="editComment">
                        @Html.Action("EditTopicComment", "TopicComment", new { topicCommentId = item.TopicCommentId })
                    </div>
                }

            </div>
            <hr />
        </div>
    }
}
@section scripts{
    @Scripts.Render("~/bundles/jquery-ui")
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#editComment").dialog({
            autoOpen: false,
            height: 380,
            width: 800,
            title: "Comment",
            show: {
                effect: "blind",
                duration: "1000"
            },
            hide: {
                effect: "explode",
                duration: "1000"
            },
            modal: false,
            resizable: false,
            dialogClass: 'no-close success-dialog'
        });
        $("#btnEdit").click(function () {
            $("#editComment").dialog("open");
            $('#TopicCommentMessage').summernote({
                height: 200,
                focus: true
            });
            //reuse
        });

    });
</script>

ForumApplication/Views/TopicComment/TopicCommentDetails.cshtml
@model ForumApplication.Models.TopicCommentModel
@{
    ViewBag.Title = "Comment Details";
    var action = Model.TopicCommentId > 0 ? "EditTopicComment" : "AddNewTopicComment";
    var header = Model.TopicCommentId > 0 ? "Edit Comment" : "Create Comment";
    var buttonText = Model.TopicCommentId > 0 ? "Save" : "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
    @Styles.Render("~/Content/summernote")
}

    @using (Html.BeginForm(action, "TopicComment", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.TopicCommentId)
        @Html.HiddenFor(m => m.TopicStarterId)
        @Html.HiddenFor(m => m.TopicId)
        <div class="form-group">
            @*<h4>@header</h4>*@
            @Html.TextAreaFor(m => m.TopicCommentMessage, new { @class = "form-control" })
        </div>
        <div class="form-group text-center" style="margin-bottom: 0;">
            <input type="submit" value="@buttonText" class="btn btn-primary" />
        </div>
    }

@section scripts{
    @Scripts.Render("~/bundles/summernote")
}
<script type="text/javascript">
    $(document).ready(function () {
        $('#TopicCommentMessage').summernote({
            height: 200,
            focus: true
        });
    });
</script>